name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release-maven:
    name: "Release Maven"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build
        run: mvn clean install
      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.gpg_private_key }}
          gpg_passphrase: ${{ secrets.gpg_passphrase }}
          nexus_username: ${{ secrets.nexus_username }}
          nexus_password: ${{ secrets.nexus_password }}

  release-gh:
    name: "Release GH"
    needs: [release-maven]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        id: Changelog
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          REPO: ${{ github.repository }}
      - name: Create Release
        id: create_release
        # Uses sha for added security since tags can be updated
        uses: actions/create-release@8f324cdc2e5470815db0a286b4b3aa7803c0e6ef
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false
